# [作業目標]

1. [簡答題] 請問 type(...) 跟 a.dtype 這兩個語法有什麼不同？

```
print('type(a): ', type(a))
print('a.dtype: ', a.dtype)
```

2. 請撰寫一個判斷 a 的元素是否等於指定資料型態的函式

3. [簡答題] 承上題，請判斷下列三種寫法為何不正確？

```
def is_dtype(a, t):
    return a.dtype is t

def is_dtype(a, t):
    return type(a) == np.dtype(t)

def is_dtype(a, t):
    return type(a) is np.dtype(t)
```

# 作業 

### 1. [簡答題] 請問 type(...) 跟 a.dtype 這兩個語法有什麼不同？

```
print('type(a): ', type(a))
print('a.dtype: ', a.dtype)
```


dtype是陣列中的資料型態，type是資料的型態

### 2. 請撰寫一個判斷 a 的元素是否等於指定資料型態的函式，並且通過測試。



In [1]:
# 記得先 Import 正確的套件
import numpy as np

In [2]:
def is_dtype(a, t):
    return a.dtype == np.dtype(t)

In [3]:
a = np.random.randint(10, size=6) 

# 測試一
print(is_dtype(a, 'int')) # True

# 測試二
print(is_dtype(a, np.int)) # True

# 測試三
print(is_dtype(a, np.dtype('int'))) # True

True
True
True


### 3. [簡答題] 承上題，請判斷下列三種寫法為何不正確？

```
def is_dtype(a, t):
    return a.dtype is t

def is_dtype(a, t):
    return type(a) == np.dtype(t)

def is_dtype(a, t):
    return type(a) is np.dtype(t)
```

```
def is_dtype(a, t):
    return a.dtype is t
```
這個是錯的，python不會把t當成一個資料型態

# 進階題

In [4]:
#array1 = np.array(range(30))
#1.將上列陣列(array1)，轉成維度為(5X6)的 array，順序按列填充。(hint:order="F")
array1 = np.array(range(30))
a2=array1.reshape((5,6),order="F")
a2

array([[ 0,  5, 10, 15, 20, 25],
       [ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29]])

In [5]:
#2.呈上題的 array，找出被 6 除餘 1 的數的索引
np.where(a2 % 6 == 1)
#array([0, 1, 2, 3, 4]印出來的是每一列
#array([5, 0, 1, 2, 3]印出來的是每一列所對應到的欄

(array([0, 1, 2, 3, 4], dtype=int64), array([5, 0, 1, 2, 3], dtype=int64))